<!DOCTYPE html>
<html>
<head>
    <title>Bootstrap template</title>
    <meta charset="utf-8">
    <link href="../../css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="../../css/style.css" media="screen" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="../../js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="../../js/bootstrap.min.js"></script>
</head>
<body>
<?php require_once($content_view); ?>
<div class="navbar navbar-static-top">
    <nav class="navbar-inner">
        <a class="brand" href="#"><img style="padding-left: 5px;" src="../../img/shopping_cart.png" /></a>
        <ul class="nav">
            <li class="divider-vertical"></li>
            <li class="active"><a href="#"><i class="icon-home"></i> Главная</a></li>
            <li><a href="#">Товары</a></li>
            <li><a href="#">Контакты</a></li>
        </ul>
        <form class="navbar-form pull-right">
            <!-- one way -->
            <!-- <input type="text" class="span2 search-query" placeholder="Search" /> -->
            <!-- two way -->
            <input type="text" class="span2" placeholder="Название товара" />
            <button type="submit" class="btn">Поиск</button>
        </form>
    </nav>
</div>

<div class="container">
    <div class="row">
        <div class="span12 text-center back-one" >
            <div>
                <h2> САМЫЙ КРУТОЙ МАГАЗИН !!!</h2>
                <h3> ОПИСАНИЕ САМОГО КРУТОГО МАГАЗИНА </h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span10 offset1" id="main-slider-block">
            <div class="carousel slide" id="myCarousel" style="margin-bottom: 0px;">
                <ol class="carousel-indicators" >
                    <li class="active" data-target="#myCarousel" data-slide-to="0"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <!-- <li data-target="#myCarousel" data-slide-to="2"></li> -->
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="../../img/slider/slide1.jpg" />
                        <div class="carousel-caption">
                            <h4>Coffe cap one</h4>
                            <p>Coffe cap in the left side</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="../../img/slider/slide2.jpg" />
                        <div class="carousel-caption">
                            <h4>Coffe cap two</h4>
                            <p>Coffe cap in the right side</p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control left" data-slide="prev" href="#myCarousel">&lsaquo;</a>
                <a class="carousel-control right" data-slide="next" href="#myCarousel">&rsaquo;</a>
            </div>
        </div>
    </div>
</div>

<div class="container" >
    <div class="row">
        <div class="span12">
            <h2 class="h2-delimiter">Товары</h2>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <ul class="thumbnails">
                <li class="span4">
                    <div class="thumbnail">
                        <a href="#" class="thumbnail"><img src="http://placehold.it/300x200" alt=""></a>
                        <div class="caption">
                            <h3>Товар 1</h3>
                            <p>Cras justo odio</p>
                            <p><a href="#" class="btn btn-primary">Посмотреть</a></p>
                        </div>
                    </div>
                </li>
                <li class="span4">
                    <div class="thumbnail">
                        <a href="#" class="thumbnail"><img src="http://placehold.it/300x200" alt=""></a>
                        <div class="caption">
                            <h3>Товар 2</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                            <p><a href="#" class="btn btn-primary">Посмотреть</a></p>
                        </div>
                    </div>
                </li>
                <li class="span4">
                    <div class="thumbnail">
                        <a href="#" class="thumbnail"><img src="http://placehold.it/300x200" alt=""></a>
                        <div class="caption">
                            <h3>Товар 3</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <p><a href="#" class="btn btn-primary">Посмотреть</a></p>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="container" >
    <div class="row">
        <div class="span12">
            <div class="main-delimiter">&nbsp;</div>
        </div>
    </div>
</div>

<div class="footer">
    <div class="container" >
        <div class="row">
            <div class="span4 text-center">
                <p>IREN-ISHOP &copy; 2013</p>
            </div>
            <div class="span4 text-center">
                <p>9870 St Vincent Place,</p>
            </div>
            <div class="span4 text-center">
                <p>Telephone:+1 800 603 6035</p>
            </div>
        </div>
    </div>
</div>
</body>
</html>